Allow once-off sponsored transactions (#550)
* Allow sponsored once-off transactions

* update transactions examples in next-template, update preview workflows

* remove comment conditional

* add prefix check

* remove unnecessary fallback

* tidy up txexamples

* tidy modal try again

* Rename useGasEstimation to useGenericDelegatorFeeEstimation

* rename dAppSponsoredUrl to delegationUrl

* rename GD gas estimation file

* update next-template transaction examples

* update state for toast txs

* remove delegation url

---------

Co-authored-by: Luca Bandini <luca.vombato@gmail.com>

diff --git a/.github/workflows/deploy-preview.yaml b/.github/workflows/deploy-preview.yaml
--- a/.github/workflows/deploy-preview.yaml
+++ b/.github/workflows/deploy-preview.yaml
@@ -20,6 +20,19 @@ jobs:
             github.event.pull_request.head.repo.full_name != github.repository &&
             github.event.action == 'opened'
         steps:
+            - name: Check branch name prefix (for external PRs)
+              env:
+                USER_NAME: ${{ github.event.pull_request.user.login }}
+                BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
+              run: |
+                PREFIX="${BRANCH_NAME%%/*}"
+                lower_user_name="${USER_NAME,,}"
+                lower_prefix="${PREFIX,,}"
+                if [[ "$lower_prefix" != "$lower_user_name" ]]; then
+                    echo "Invalid branch name. Please ensure that your PR branch name starts with your GitHub username in the format of <username>/<branch-name>. Eg. myusername/my-feature"
+                    exit 1
+                fi
+
             - name: Comment on external PR
               uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
               with:
@@ -28,7 +41,7 @@ jobs:
                       ## 👋 Thanks for your contribution!
                       
                       Since this PR comes from a forked repository, preview deployment requires approval from a maintainer for security reasons.
-                      Please ensure that your PR is coming from a meaningful branch name. Eg. feature/my-feature **not main**
+                      Please ensure that your PR branch name starts with your GitHub username in the format of <username>/<branch-name>. Eg. myusername/my-feature **not main**
                       
                       **Next steps:**
                       1. A maintainer will review your code
@@ -56,6 +69,19 @@ jobs:
             AWS_REGION: eu-west-1
             BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
         steps:
+            - name: Check branch name prefix (for external PRs)
+              if: github.event.pull_request.head.repo.full_name != github.repository
+              env:
+                USER_NAME: ${{ github.event.pull_request.user.login }}
+              run: |
+                PREFIX="${BRANCH_NAME%%/*}"
+                lower_user_name="${USER_NAME,,}"
+                lower_prefix="${PREFIX,,}"
+                if [[ "$lower_prefix" != "$lower_user_name" ]]; then
+                    echo "Invalid branch name. Please ensure that your PR branch name starts with your GitHub username in the format of <username>/<branch-name>. Eg. myusername/my-feature"
+                    exit 1
+                fi
+
             - name: Checkout
               uses: actions/checkout@v4
               with:
@@ -97,10 +123,18 @@ jobs:
               run: |
                   AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_PREVIEW_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/' '/*'
 
+            - name: Find Comment
+              uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
+              id: find-comment
+              with:
+                  issue-number: ${{ github.event.pull_request.number }}
+                  comment-author: 'github-actions[bot]'
+                  body-includes: 🚀 Preview environment deployed!
+
             - name: Create Deployment Comment
-              if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.pull_request.draft == true
               uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
               with:
+                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                   issue-number: ${{ github.event.pull_request.number }}
                   body: |
                       # 🚀 Preview environment deployed!
